apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: circle-prod
  labels:
    app: circle-of-trust
    component: migration
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: db-migration
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: migrate
          image: backend
          command:
            - /bin/sh
            - -c
            - |
              echo "Running database migrations..."
              # Add your migration command here, e.g.:
              # alembic upgrade head
              # or
              # python manage.py migrate
              echo "Migrations completed successfully"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: circle-secrets
                  key: DATABASE_URL
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
