apiVersion: v1
kind: ServiceMonitor
metadata:
  name: circle-backend-monitor
  namespace: circle-prod
  labels:
    app: circle-of-trust
    component: backend
spec:
  selector:
    matchLabels:
      app: circle-backend
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: circle-frontend-monitor
  namespace: circle-prod
  labels:
    app: circle-of-trust
    component: frontend
spec:
  selector:
    matchLabels:
      app: circle-frontend
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: circle-alerts
  namespace: circle-monitoring
  labels:
    app: circle-of-trust
spec:
  groups:
    - name: circle-of-trust.rules
      interval: 30s
      rules:
        - alert: HighErrorRate
          expr: |
            rate(http_requests_total{status=~"5.."}[5m]) > 0.05
          for: 5m
          labels:
            severity: critical
            component: backend
          annotations:
            summary: "High error rate detected"
            description: "Error rate is {{ $value }} for {{ $labels.instance }}"
        
        - alert: PodCrashLooping
          expr: |
            rate(kube_pod_container_status_restarts_total{namespace="circle-prod"}[15m]) > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.pod }} is crash looping"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is restarting frequently"
        
        - alert: HighMemoryUsage
          expr: |
            container_memory_usage_bytes{namespace="circle-prod"} / container_spec_memory_limit_bytes{namespace="circle-prod"} > 0.9
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage detected"
            description: "Container {{ $labels.container }} is using {{ $value | humanizePercentage }} of memory limit"
        
        - alert: HighCPUUsage
          expr: |
            rate(container_cpu_usage_seconds_total{namespace="circle-prod"}[5m]) > 0.8
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected"
            description: "Container {{ $labels.container }} CPU usage is {{ $value | humanizePercentage }}"
        
        - alert: DeploymentReplicasMismatch
          expr: |
            kube_deployment_spec_replicas{namespace="circle-prod"} != kube_deployment_status_replicas_available{namespace="circle-prod"}
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Deployment replica mismatch"
            description: "Deployment {{ $labels.deployment }} has {{ $value }} replica mismatch"
        
        - alert: PersistentVolumeUsageHigh
          expr: |
            kubelet_volume_stats_used_bytes{namespace="circle-prod"} / kubelet_volume_stats_capacity_bytes{namespace="circle-prod"} > 0.85
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "PV usage high"
            description: "PV {{ $labels.persistentvolumeclaim }} is {{ $value | humanizePercentage }} full"
